title: SRE at HelloFresh
description: Becoming an SRE
author: Brian Greenhill
github: https://github.com/bghellofresh
about: I am an SRE at HelloFresh
disqus_shortname: punkshui
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: false
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/Tweeeteeeer"
    - icon: fa-github
      link: "https://github.com/bghellofresh"

share:
  twitter_username: Tweeeteeeer

urls:
    - text: About
      url: /about/
    # - text: My Projects
    #   url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://localhost:4000"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
